language: node_js
node_js:
  - "lts/*"
services:
  - rabbitmq
before_script:
  - sudo rabbitmq-plugins enable rabbitmq_management && rabbitmqadmin export rabbit.definitions.json && cat rabbit.definitions.json
